### ISSUE TITLE
spacy example does not work as advertised

### ISSUE THREAD

**Issue by reckart** [inception-project/inception-external-recommender#19]
When putting the spacy example shown in the README file into a py file and running it, it produces an error:

```
OSError: [E941] Can't find model 'en'. It looks like you're trying to load a model from a shortcut, which is deprecated as of spaCy v3.0. To load the model, use its full name instead:

nlp = spacy.load("en_core_web_sm")
```

**Comment by DavidHuebner** [comment]
Sorry, to intervene here, but I believe that this issue needs another little change.
Right now, when I execute the `SpacyPosClassifier` pipelines, then all pos tags are empty strings. 
The reason are twofold:

1. The `tagger` pipelines needs the existence of word embeddings. Hence, one needs to manually call `self._model.get_pipe("tok2vec")(doc)` before calling `self._model.get_pipe("tagger")(doc)`
2. The information about the PoS tags in Spacy v3 is now saved in `spacy_token.tag_` instead of `spacy_token.pos_`.

Please also see my discussion here: https://github.com/explosion/spaCy/issues/7105#

BTW: Unfortunately, the spacy test is not capturing the problem because all PoS-values are empty strings, i.e. not `None` and hence, the following assert is not triggered.
``` python
for prediction in predictions:
    assert getattr(prediction, PREDICTED_FEATURE) is not None
```

**Comment by jcklie** [comment]
Thank you for the report. I changed the recommender and the test, I hope it works now.
